CREATE TABLE QUESTION(
ID BIGINT PRIMARY KEY,
QUESTION VARCHAR(255),
AUTHOR VARCHAR(255),
DIFFICULTY VARCHAR(255),
EXAMINE_ID BIGINT
);

CREATE TABLE ANSWER(
ID BIGINT PRIMARY KEY,
NAME VARCHAR(255),
QUESTION_ID BIGINT
);

CREATE TABLE EXAMINE(
ID BIGINT PRIMARY KEY,
NAME VARCHAR(255),
);

CREATE TABLE RESULT(
ID BIGINT PRIMARY KEY,
RESULT VARCHAR(255),
USER_ID BIGINT
);

CREATE TABLE [USER](
ID BIGINT PRIMARY KEY,
LOGIN VARCHAR(255),
PASSWORD VARCHAR(255),
NAME VARCHAR(255),
);

ALTER TABLE QUESTION(
ADD FK_EX FOREIGN KEY EXAMINE_ID REFERENCES EXAMINE (ID)
);

ALTER TABLE ANSWER(
ADD FK_QU FOREIGN KEY QUESTION_ID REFERENCES QUESTION (ID)
);

ALTER TABLE RESULT(
ADD FK_US FOREIGN KEY USER_ID REFERENCES [USER] (ID)
);